### ISSUE TITLE
alloc-fmt: Allow disabling backtrace

### ISSUE THREAD

**Issue by joshlf** [ezrosent/allocators-rs#108]
Currently, `alloc-fmt` always tries to print a backtrace, although that often fails because printing the backtrace involves allocation (we detect this failure and just abort). It'd be nice if the user could decide at compile time (or maybe even at runtime?) whether they wanted backtraces.

Two options I see for this:
- Add a feature (we probably want it included in the crate's list of default features) that enables backtraces
- Add the ability to parse the `RUST_BACKTRACE` environment variable according to how it is used in normal Rust. This one is tricky because it should ideally be done in a way that avoids allocation (allocating is not the end of the world so long as, just like with backtraces, we can detect any recursion and abort)

**Comment by Yarn** [comment]
i'll give this a shot

**Comment by joshlf** [comment]
Awesome, thanks! I'm happy to mentor if you need any help with any of the existing codebase, allocator weirdness, etc.

**Comment by DemiMarie** [comment]
Could we print out a backtrace without allocating, using a static buffer?

**Comment by joshlf** [comment]
Right now, we use the [`backtrace`](https://crates.io/crates/backtrace) crate, and we're at its mercy. I've tried in [`print_backtrace_and_abort`](https://crates.io/crates/backtrace) to use the lowest-level API that it exposes, but if that allocates, there's nothing we can do about it.

I'm afraid that making progress on this issue is likely going to require getting into the weeds with how the `backtrace` crate is implemented, or coming up with another solution (that doesn't involve `backtrace`) from whole cloth.

**Comment by Yarn** [comment]
any guidance on how I should test changes? alloc-fmt doesn't seem to have its own tests.

**Comment by joshlf** [comment]
Yeah testing is unfortunately pretty tricky. If you want to test to make sure that it just works properly (ie, actually prints a backtrace), you can run `cargo run --bin assert <arg>` (see `src/bin/assert.rs` for possible arguments).

However, that won't help you determine whether your method of printing backtraces allocates. For that, you'll need to actually cause a panic from inside the global allocator. Your best bet is probably to add an explicit panic to elfmalloc's `malloc` implementation (`c_malloc` in `elfmalloc/src/alloc_impl.rs`), and then test a simple program using `elfc`. I'd suggest something like:

```c
#include<stdlib.h>
#include<stdio.h>

int main() {
	printf("%p\n", malloc(8));
}
```

In order to run it with elfmalloc, you'll first need to `cargo build` in `elfc`, and then use `LD_PRELOAD` (assuming you're on Linux) to load it as a dynamic library. So, in total:

```text
$ gcc -o alloc alloc.c     # compile the simple C program
$ cargo build              # build elfc
$ LD_PRELOAD=./target/debug/libelfc.so ./alloc
```

If your code works properly, then running `./alloc` should print the panic message and print a backtrace before aborting. If your code still allocates while calculating the backtrace, you'll probably see the panic message (possibly twice), but then the program will abort without printing a stack trace.

**Comment by Yarn** [comment]
First off, sorry for the slow progress, just haven't been getting around to things.

I made printing backtraces a feature. (https://github.com/Yarn/allocators-rs/commit/ef74bc82409de7f078541ea2c2d6bb0ed2b55684)

You can run it without backtraces using
`rustup run nightly cargo run --no-default-features --bin assert assert`

For testing it looks like I should be able to add

`RUST_BACKTRACE=1 travis-cargo --no-default-features --only nightly run -- --bin print`

`RUST_BACKTRACE=1 cargo run --no-default-features -- --bin print`

to `travis.sh` and `appveyor.sh`

This should at least make sure it builds.

Is that what you want for testing?

---

For using an environment variable I found the relevant code in std which is probably a decent start.

https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/os.rs#L383

The other option would be to check the env variable at compile time but this would have some surprising behavior. (e.g. run program, see panic, set env variable would require making a change to make it recompile afaik) I'm not sure how RUST_BACKTRACE is handled normally.

**Comment by joshlf** [comment]
Looks good, thanks!

For environment variables, let's hold off for the time being and just get a PR that adds the feature. Even looking at the [functions exposed in libc](https://www.gnu.org/software/libc/manual/html_node/Environment-Access.html#Environment-Access), it looks like they probably allocate under the hood (since they return strings). Figuring out how to do allocation-free environment variable lookup is probably going to be pretty tricky. You should of course feel free to take a stab at it, but it's probably better to save it for a second PR so we can get the feature stuff you've already done added.

As for testing, what you've suggested looks good.

**Comment by Yarn** [comment]
https://github.com/ezrosent/allocators-rs/pull/130

**Comment by joshlf** [comment]
Closed in #130.

**Comment by Yarn** [comment]
@joshlf 

btw, I looked into using environment variables. Rust's std makes it memory safe by wrapping env variable access in a global rw lock (and isn't safe . If we read env variables it wouldn't be memory safe if any other code changes env variables (including with the rust std). As far as i can tell there isn't any way around that.

**Comment by joshlf** [comment]
Yeah, I'm not too worried about it. The fact that we print the error first before printing the backtrace at least means that if the backtrace crashes, we'll still get the error itself.

**Comment by Yarn** [comment]
Memory unsafety has concerns beyond just crashing. If the soundness of the env variable handling really isn't an issue I'll finish that up when I get the chance.

**Comment by joshlf** [comment]
Is there perhaps a way that we could read the variable such that it might give us garbage, but it won't cause memory unsafety? E.g., if we read the variable and find that its contents are `RUST_0A9KTXACX=1`, that's fine - we'll just not print a backtrace. We just don't want to read unmapped memory (a segfault) or cause UB.

**Comment by Yarn** [comment]
In memory you have a null terminated array of pointers to null terminated c strings. If the array of pointers gets overwritten with something else it could obviously segfault, I don't see a way around this. If you read the string gets overwritten by something without a null terminator that could also segfault if you don't hit some other null (but if you are looking for "RUST_0A9KTXACX=1" exactly or such you could just limit the length and mostly mitigate that). As for other UB, none comes to mind immediately but that doesn't mean it's not there.

I think all of this requires another thread to change environment variables in the first place though. I still wouldn't be comfortable having this without it being behind a feature flag with a big warning about what could introduce memory unsafety in safe code.
