### ISSUE TITLE
elfmalloc: Implement malloc-bind::LayoutFinder

### ISSUE THREAD

**Issue by joshlf** [ezrosent/allocators-rs#12]
In order to allow us to use `malloc-bind` to create C API bindings for `elfmalloc`, we need an implementation of the `malloc-bind::LayoutFinder` trait, which maps from allocated objects to their layouts. All of the logic to do that already exists in `elfmalloc` - it just needs to be encapsulated in a `LayoutFinder` implementation.

**Comment by dobkeratops** [comment]
just registering my interest in an allocator where where size/align is passed back into free .. 'user-tracks-the-size'. I'd be very interested in an allocator built for this from the ground up, with the 'C-like' malloc/free being emulated on the top of it. (I'm not completely familiar with how rust does this, but I gather rust *has* been setup to interface with this style of allocation, which is great to know. see also c++ operator delete overloads with (void*,size_t) and the more recent modern c++ extentions for the 'array allocator delete[]' to also support that)

**Comment by joshlf** [comment]
@dobkeratops Some links for you to check out if you're interested in how Rust does this:
- The Rust [`Alloc`](https://doc.rust-lang.org/nightly/alloc/allocator/trait.Alloc.html) trait
- The [original RFC](https://github.com/rust-lang/rfcs/blob/master/text/1398-kinds-of-allocators.md) that proposed the current system

**Comment by dobkeratops** [comment]
thanks, ok if I'm reading this right 'Layout' is does basically just encapsulate Size,Align, (and seems to do error checking to enforce align= a power-of-2 , I guess.).. as far as I can see the allocator interface itself always takes layouts, never returns them, which would be as correct.

**Comment by joshlf** [comment]
Yep, that's exactly right. And the idea is that you provide the same `Layout` on `dealloc` (or `realloc` or any other similar method) that you provided on `alloc`.

**Comment by joshlf** [comment]
Closed by #46.
