### ISSUE TITLE
alloc-tls: update crates.io

### ISSUE THREAD

**Issue by sollyucko** [ezrosent/allocators-rs#196]
[The crates.io crate](https://crates.io/crates/alloc-tls) does not include commit dec3843. Could you publish the changes?

**Comment by joshlf** [comment]
I will once this is resolved: https://github.com/rust-lang/rust/issues/70673

**Comment by sollyucko** [comment]
I can't reproduce the ICE. Maybe try deleting `Cargo.lock` and `target/` and rebuilding, since it might be an issue with an old version of a dependency?

**Comment by joshlf** [comment]
It happens for me even after removing `Cargo.lock` and `target/`. Probably worth pointing out that I'm on macos. Are you as well? I'd also check that you're on the same toolchain version that I cited in that issue (latest nightly).

**Comment by sollyucko** [comment]
I'm running the same rustc version, but on Debian.

**Comment by joshlf** [comment]
That doesn't surprise me. alloc-tls has some pretty wacky platform-dependent code. It wouldn't surprise me if the macos-specific bits exercised some little-used corner of the compiler.

**Comment by joshlf** [comment]
Out of curiosity, what are you using `alloc-tls` for?

**Comment by sollyucko** [comment]
I'm working on a project involving parallel computation and caching, but I wasn't sure how to start, so I just downloaded everything I might need, but I probably don't actually need this.

**Comment by joshlf** [comment]
Ah. Yeah seems unlikely that you need to depend on this directly. It would be more likely that you'd need to depend on one of its dependents.
