### ISSUE TITLE
elfmalloc-performance.md: Confusing graphs

### ISSUE THREAD

**Issue by jplatte** [ezrosent/allocators-rs#34]
Apart from the fact that the axes on these graphs could be much more readable, a few of them have duplicate titles, in one case (the shbench graphs) there isn't even any text in between the two sets of identically named graphs. Suggestions:

* Clarify the difference between the first two and the latter two graphs for the shbench comparison
* Remove the titles from the graphs themselves and add them to the markdown, so they can be searched
* Get rid of the weird scientific notation y axis on the first producer-consumer graph
* Put units on the graph axis labels instead of in the title of the graph

**Comment by ezrosent** [comment]
Thanks for catching this and filing the issue. I think these suggestions are reasonable; I should have time to update the graphs and markdown today.

**Comment by ezrosent** [comment]
Also, as for the identically-named graphs. The first set uses smaller objects and the second set is for medium-sized objects. I'll make sure that's clear.

**Comment by ezrosent** [comment]
Closed by #41

**Comment by jplatte** [comment]
Just to be clear, I wasn't saying that you should put the title left of the Y axis, but that each of the ticks on the Y axis should have the unit in its label, e.g. "10000 KB", "20000 KB", ... for the first graph [and maybe use MB for that graph too ;)]

But still an overall improvement, thanks for that!
