### ISSUE TITLE
Travis: Spurious test failures on Mac

### ISSUE THREAD

**Issue by joshlf** [ezrosent/allocators-rs#36]
Our [Travis CI tests](https://travis-ci.org/ezrosent/allocators-rs) are failing on Mac before the core of the tests even gets executed. I suspect it's related to [this issue](https://github.com/travis-ci/travis-ci/issues/6307), but I haven't been able to verify this.

**Comment by joshlf** [comment]
Apparently specifying XCode 8.3 (See PR #66 ) doesn't fix it either.

**Comment by kennytm** [comment]
I'm pretty sure the error is 

```
./travis.sh: line 13: travis-cargo: command not found
```

Are you sure the PATH is set correctly? I don't think pip on macOS uses `~/.local/bin`.

```
$ pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
```

**Comment by joshlf** [comment]
Oh interesting, earlier builds were failing earlier than this. Not sure what I changed, but yeah that seems like an easier error to deal with.

**Comment by joshlf** [comment]
But unfortunately we've already got the following directive in `.travis.yml`:

```yml
before_script:
  - pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
```

You can see it getting executed successfully [here](https://travis-ci.org/ezrosent/allocators-rs/jobs/284891277#L70).

**Comment by kennytm** [comment]
I mean on macOS when you `pip install --user` the packages are placed into `~/Library/Python/X.Y/bin/` instead of `~/.local/bin`.

**Comment by joshlf** [comment]
OH sorry I misread your comment. I'll take a look at that.

**Comment by opilar** [comment]
You should consider using `python -m site --user-base` instead.
Look at the [similar issue](https://github.com/rust-lang-nursery/lazy-static.rs/pull/74/files).

**Comment by joshlf** [comment]
Good recommendation; I'll do that. Thanks!

**Comment by joshlf** [comment]
Thanks for all the help, folks, that worked!

**Comment by joshlf** [comment]
@kennytm Have you seen this issue crop up for XCode 8.3 in particular? In moving from `pip` to `pip2` to support Travis making XCode 8.3 the default, we're getting this error again. See, e.g., [this build](https://travis-ci.org/ezrosent/allocators-rs/jobs/311546884) that fails with `/Users/travis/.rvm/scripts/functions/support: line 57: shell_session_update: command not found`.

**Comment by kennytm** [comment]
@joshlf I haven't seen this as I'm not using travis-cargo 😛 The error seems to be related to `rvm`, not Python though. Try https://github.com/direnv/direnv/issues/210#issuecomment-225878154?

**Comment by joshlf** [comment]
Cool that worked, thanks! Sorry for branding you the Travis Mac expert :P
