### ISSUE TITLE
Add AppVeyor testing

### ISSUE THREAD

**Issue by retep998** [ezrosent/allocators-rs#39]
Because this set of crates is at least attempting to support Windows, it should have CI testing on AppVeyor to make sure the Windows support is working.

**Comment by joshlf** [comment]
We were actually planning on doing that tonight :) I know you have a lot more Windows experience than we do, though, so if you're interested, I'm sure the PR will be open for a while as I try to get things working. We'd be happy to have contributions!

**Comment by joshlf** [comment]
PR is open: #40

**Comment by joshlf** [comment]
Closed in #40.
